### ISSUE TITLE
Row names issue while integrating BAI

### ISSUE THREAD

**Issue by slopezal** [MortonArb-ForestEcology/URF2017#2]
I can convert ring widths to BAI without an issue but R isn't able to rbind the individual files together once the BAI information is attached. [Compile_TreeData.R](https://github.com/MortonArb-ForestEcology/URF2017/blob/master/scripts/Compile_TreeData.R), line 161 - 168) The error messages says that the row names need to be unique, even if I change them it refuses to accept it. Furthermore, once the BAI information has been merged changing the row names doesn't actually change anything, they have to be changed in the BAI file (bai.tmp). I think the issue is that the bai.out function is protecting the row name information in an attempt to conserve the year however it's just getting in the way and I'm not sure how to handle it.

**Comment by crollinson** [comment]
I've been playing with this for a bit, but this is acting very weird.  I have time to try a couple things, but you may have to re-structure your loop.  The bai functions are generally meant to work with all of your RW data in columns of a single matrix and your DBHs in a column for a separate object (making sure to keep the orders the same).

**Comment by crollinson** [comment]
Fixed it & pushed it!  Just over-wrote the row names for bai.tmp before doing rbind.  Not an elegant hack & I don't recommend copying this code down the line.  It's a super ugly hack, but it should work.
